---
apiVersion: v1
kind: Service
metadata:
  name: websockets-test
spec:
  type: ClusterIP
  ports:
    - name: websocket
      protocol: TCP
      port: 8088
      targetPort: 80
  selector:
    app: websockets-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websockets-test
spec:
  selector:
    matchLabels:
      app: websockets-test
  template:
    metadata:
      labels:
        app: websockets-test
    spec:
      containers:
        - name: websockets-test
          image: ghcr.io/johefernan/websockets-test:1.0
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 5
          ports:
            - containerPort: 8088
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: websocket-test
spec:
  hosts:
  - localhost
  gateways:
  - bitso-gateway
  http:
  - name: match-0
    match:
     - uri:
         prefix: "/"
#     - uri:
#         prefix: "/inemuri"
#     - uri:
#         prefix: "/seppuku"
    route:
    - destination:
        host: "websockets-test.default.svc.cluster.local"
        port:
          number: 8088
      weight: 100
    timeout: 30s

